### ISSUE TITLE
Chapter 2: Physical bounds figure

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#16]
* Need subfigures (a), (b), etc.
* Make plots in matlab
* Change caption to say that an option is that the boundary is so far away (but can't see it).
* Export as .pdf to make it sharper (visually)
* Add vertical label: red: planetary boundary (carrying capacity). blue: impactor (impacts)

* One line should be dashed.

* Convert to ggplot (no scales)

* Jeremy to provide equations to Matt (or Matt teach Jeremy)

**Comment by MatthewHeun** [comment]
After seeing the graphs today, I'm even more convinced that we should ggplot-ify the four subfigures to ensure consistency (size, colors, etc.) within this figure and across the book itself.

**Comment by jgvanantwerp** [comment]
Pretty much the issue was the bounding boxes on the PDFs. 
Here's the Matlab code for the figures (.m files won't attach).
figure(1)
subplot(221)
% Limits are distant or growing
t=0:.01:2;
y=exp(t);
plot(t,y,'LineWidth',3)
hold on
plot(t,y+4*ones(1,length(y)),'-.','LineWidth',3)
set(gca,'xtick',[])
set(gca,'ytick',[])
xlabel('Time')

figure(2)
subplot(221)
% Limits are seen
sys1=tf(3,[0.1 1 1]);
sys2=tf(1,[1 1]);
[x2, t2]=step(sys1*sys2,6);
plot(t2, x2,[0 6],[3.25 3.25],'-.','LineWidth',3)
set(gca,'xtick',[])
set(gca,'ytick',[])
xlabel('Time')

figure(3)
subplot(221)
% Oscillations due to delayed signals but robust bounds
sys3=tf(1,[.81 .15 1]);
sys3lim=-0.5*sys3*sys2;
[x3, t3]=step(sys3,15);
[x3a, t3a]=step(sys3lim,15);
plot(t3, x3,'LineWidth',3)
hold on
plot(t3a, x3a+1.75,'-.','LineWidth',3)
set(gca,'xtick',[])
set(gca,'ytick',[])
xlabel('Time')

figure(4)
subplot(221)
% Erodable bounds

% sys4=sys2*sys2*tf([1 -0.9],[4 1 1]);
% [x4, t4]=step(sys4,15);
% sys5=2*tf([5 -1],[4 1 1]);
% [x5, t5]=step(sys5,15);
% plot(t4, [x4+1 -x4])
t6=0:0.01:15;
x6=1./(1+exp(0.1*t6.^1.6-3.5));
t5=0:1:15;
x5=[.37 .39 .45 .55 .71 .93 1.21 1.44 1.37 1.15 .85 .45 .3 .15 .15 .15];
%plot(t6, x6)
plot(t5, x5,'LineWidth',3)
hold on
plot(t6, x6+.3,'-.','LineWidth',3)
xlabel('Time')
set(gca,'xtick',[])
set(gca,'ytick',[])

**Comment by MatthewHeun** [comment]
At this point, the only remaining item is to make a equation for the up-then-down line.

**Comment by MatthewHeun** [comment]
Check file F2point3D.xlsx for data for this subplot

**Comment by jgvanantwerp** [comment]
generated new data.

**Comment by MatthewHeun** [comment]
Added new graph in the figure. 

<img width="445" alt="image" src="https://user-images.githubusercontent.com/3308246/146858637-d4ebe795-47de-41d4-b75e-c7be80c25b46.png">

Looks pretty good!
