### ISSUE TITLE
Add Collapse to Ch2 further reading

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#174]
Tania Sousa suggests:

Jared Diamond has a book "Collapse" where he has a nice chapter on Easter Island :-)

**Comment by MatthewHeun** [comment]
I interpret this question as 

* suggesting an additional "further reading" item and 
* adding a reference to the question.

These seem like easy things to do and I suggest we do them.

**Comment by jgvanantwerp** [comment]
Jared Diamond gained a lot of attention (in the popular press) when Collapse was published in 2005. Since then, it has been met with quite a lot of skepticism and criticism from academics. Given how controversial it is, I'd rather not associate our with with Collapse directly. I think we can make our points independently of Diamond.
