### ISSUE TITLE
Indoor water

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#208]
In response to "Rain water is an ecosystem service" in Section 9.2.1, Paul Brockway asked:

what about water for indoor use?

**Comment by MatthewHeun** [comment]
JVA will need to decide how to deal with this comment.

**Comment by jgvanantwerp** [comment]
My inclination is to ignore - unless I'm missing something. Paul's comment strikes me as completely off the wall. Perhaps he didn't understand my point (likely, because I didn't elaborate) or what he's brought up is irrelevant. My point was that the rain irrigates crops without a farmer having to do anything active (like artificial irrigation). Is Paul asking whether water that is used indoors is an ecosystem service? (Maybe in some respects it is.) But I was talking about outdoor water.

I think the deciding factor should be that this chapter is about agriculture, not about ecosystem services.
