### ISSUE TITLE
We need to mention CH4 from cows, etc.

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#209]
In response to "However, the most globally important form of air emissions is greenhouse gases" in Section 9.2.2, Paul Brockway wrote:

in your text below i think you dont say anythign about the methane emissions from cows etc? i thought that was a major source of agricultural GHG emissions?

**Comment by MatthewHeun** [comment]
We should get some data and possibly tone down the "most important" part of the sentence in question. And we should talk about CH4 emissions from livestock somewhere in Ch9.

**Comment by jgvanantwerp** [comment]
Yes. Another on my mental list. I'm generally unhappy with how this chapter ended, in part because I think I don't understand the data well enough. Regenerative agriculture needs to be in this chapter. Generally, that means animal manure. We don't want ecosystems without animals and I think we won't count wild animal emissions towards GHG emissions. Wild vs. domestic feels like a false dichotomy. So is our cow budget out of bounds? I've seen some data to suggest cow impact isn't that bad -- if you do agriculture right. Anyway, I think this chapter needs a bit of a re-write, to include at least regenerative agriculture, a discussion about cows and boundaries. Oh, and also, fertilizer use (particularly phosphates) are only weakly sustainable.

**Comment by jgvanantwerp** [comment]
Done.
