### ISSUE TITLE
Maximize GDP?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#215]
In Section 10.1.2, in response to "Or we might try to maximize GDP," Paul Brockway wrote:

how woudl that help sustainabilty? maximise GDP = maximising resource use = sounds a bad idea

**Comment by MatthewHeun** [comment]
Would be good for JVA to clarify here.

**Comment by jgvanantwerp** [comment]
Since land is a limited resource, it makes sense to maximize the effective use 
of that resource, whether that's for food, housing, and/or ecosystem services.
Various metrics could be used to gauge the effectiveness of land use.
...
For cities, we could attempt to maximize population density, or we could minimize
metrics related to impact, or ... we might try to maximize urban GDP.
However, we also care about ecosystem service and the health of the environment 
that provides those ecosystem services.
We care about multifactor indices: biodiversity, wilderness, ecosystem services, 
air and water quality, etc.
*Text box with Vern Ehlers quote*
Then we talk about the sparing/sharing dichotomy.

**Comment by jgvanantwerp** [comment]
Matt, can you suggest a clarification?

**Comment by MatthewHeun** [comment]
I took a crack at an edit of Section 10.1.2. JVA should take a look and close this Issue if he is satisfied that my edit or a subsequent revision is sufficient.

**Comment by MatthewHeun** [comment]
Will be swept up in JVA review of Ch10.
