### ISSUE TITLE
Blurry lines between individual and collective actions

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#261]
Ch11 is about collective actions. Ch12 is about individual actions. But the line is sometimes blurry. A discussion question that owns the blurriness would be helpful. 

Suggested location: Ch12.

**Comment by MatthewHeun** [comment]
Put at end of 11.1 (before 11.1.1)?

**Comment by MatthewHeun** [comment]
Or at end of Section 12.1 (or maybe right before Section 12.1)

**Comment by jgvanantwerp** [comment]
Discussion question for chapter 12:
Consider the relationship between individual action and collective action. Because humans live in societies, every collective action is composed of many individual actions. P4.8 illustrates the impossibility trying to divorce the individual from the collective. Do you consider voting an individual action or a collective action? How about going to a climate-change protest rally? Is going to the rally different than organizing the rally? Wangari Maathai (Section 12.1) was an originator of the Green Belt Movement. Was that an individual or collective action? Do you consider individual or collective actions to be more valuable for sustainability? Is individual versus collective a helpful framework for thinking about sustainability or a false dichotomy?

**Comment by MatthewHeun** [comment]
Edited the question a bit and added. Done.
