### ISSUE TITLE
Sentence needs simplifying

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#337]
The middle sentence in this paragraph from Ch3 needs simplification.

In a developing society (low \mft{A}),
birth rates and death rates (per thousand per year) are high but nearly balanced, 
resulting in low population growth.
Demographic transition theory,\index{demographic transition theory}
illustrated schematically in Figure~\ref{fig:dtt},
is the observed pattern, shown in the top of Figure~\ref{fig:dtt},
that economic development leads to decreased mortality 
followed some time later by a falling birth rate.
Thus, as shown in the middle section of Figure~\ref{fig:dtt}, 
population is predicted to grow rapidly and then stabilize.

**Comment by jgvanantwerp** [comment]
Demographic transition theory,\index{demographic transition theory}
is based on an observed pattern of population change thought to be caused by
economic development.
Figure~\ref{fig:dtt} illustrates schematically the four stages of the transition.
In a developing society (low \mft{A}),
birth rates and death rates (per thousand per year) are high but nearly balanced,
resulting in low population growth.
Later, the birth rate falls.
Thus, population is predicted to first grow rapidly and then stabilize.
